param_space:
  modalidad:           [FLAIR, RGB]
  modelo:              [mask_rcnn_R_50_FPN_1x.yaml,
                        mask_rcnn_R_50_FPN_3x.yaml,
                        mask_rcnn_R_101_FPN_3x.yaml,
                        mask_rcnn_R_50_C4_1x.yaml,
                        mask_rcnn_R_50_C4_3x.yaml, 
                        mask_rcnn_R_101_C4_3x.yaml,
                        mask_rcnn_R_50_DC5_1x.yaml,
                        mask_rcnn_R_50_DC5_3x.yaml,
                        mask_rcnn_R_101_DC5_3x.yaml,
                        mask_rcnn_1_101_32x8d_FPN_3x.yaml]
  maxiter_steps: 
    - { max_iter: 2000,  steps: [1000] }
    - { max_iter: 5000,  steps: [2500] }
    - { max_iter: 10000, steps: [5000] }
  base_lr:             [0.00025]
  gamma:               [0.1]
  batch_size:          [2, 8, 16]
  flip:                [horizontal, vertical, none]
  weight_decay:        [0.0001]
